"""Fetch the Korean fonts and write compact subsets into assets/fonts/.

Why: Chromium's PDF backend embeds variable fonts and CFF (.otf/.ttc) fonts as Type3
glyph programs. Static TrueType (glyf) fonts embed as proper CID fonts with selectable,
searchable text, so the deck uses static TTF sources subset to the glyphs we need
(KS X 1001 Hangul 2,350 + every character used in deck/ and video/ + punctuation).

  python3 tools/fonts.py          # re-run after adding text with rare Hangul syllables

Sources (SIL Open Font License 1.1): Pretendard (npm "pretendard"),
Noto Serif KR (Google Fonts).
"""
import re
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cache" / "fonts"
OUT = ROOT / "assets" / "fonts"

PRETENDARD = {300: "Light", 400: "Regular", 500: "Medium", 600: "SemiBold", 700: "Bold"}
SERIF_WEIGHTS = [300, 400, 500, 600]


def fetch_pretendard():
    pkg = CACHE / "package"
    if not (pkg / "dist").exists():
        CACHE.mkdir(parents=True, exist_ok=True)
        subprocess.run(["npm", "pack", "pretendard", "--silent"], cwd=CACHE, check=True)
        tgz = sorted(CACHE.glob("pretendard-*.tgz"))[-1]
        with tarfile.open(tgz) as t:
            t.extractall(CACHE)
    return {w: pkg / "dist/public/static/alternative" / f"Pretendard-{n}.ttf" for w, n in PRETENDARD.items()}


def fetch_serif():
    out = {}
    css_url = "https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@" + ";".join(map(str, SERIF_WEIGHTS))
    need = [w for w in SERIF_WEIGHTS if not (CACHE / f"NotoSerifKR-{w}.ttf").exists()]
    if need:
        CACHE.mkdir(parents=True, exist_ok=True)
        req = urllib.request.Request(css_url, headers={"User-Agent": "Mozilla/4.0"})  # old UA -> TTF urls
        css = urllib.request.urlopen(req).read().decode()
        for w, url in re.findall(r"font-weight: (\d+);\s*src: url\((https://[^)]+\.ttf)\)", css):
            path = CACHE / f"NotoSerifKR-{w}.ttf"
            if not path.exists():
                urllib.request.urlretrieve(url, path)
    for w in SERIF_WEIGHTS:
        out[w] = CACHE / f"NotoSerifKR-{w}.ttf"
    return out


def charset():
    chars = set()
    for code in range(0xAC00, 0xD7A4):  # KS X 1001 Hangul (the 2,350 common syllables)
        try:
            if len(chr(code).encode("euc-kr")) == 2:  # 8-byte make-up sequences are not KS X 1001
                chars.add(code)
        except UnicodeEncodeError:
            pass
    for a, b in [(0x20, 0x7E), (0xA0, 0xFF), (0x2010, 0x205E), (0x2190, 0x21FF), (0x2460, 0x24FF),
                 (0x25A0, 0x25FF), (0x3000, 0x303F), (0x3131, 0x318E), (0x3200, 0x321E), (0xFF01, 0xFF5E),
                 (0x2200, 0x222B)]:
        chars.update(range(a, b + 1))
    for d in ("deck", "video"):
        for p in (ROOT / d).glob("*"):
            if p.suffix in (".html", ".js", ".json", ".py", ".txt", ".md"):
                chars.update(ord(c) for c in p.read_text(encoding="utf-8", errors="ignore"))
    return sorted(c for c in chars if c >= 0x20)


def make(src, dst, codes):
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.name_languages = ["*"]
    opts.notdef_outline = True
    opts.hinting = False
    opts.desubroutinize = True
    font = TTFont(src)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=codes)
    sub.subset(font)
    font.flavor = "woff2"
    font.save(dst)
    return dst.stat().st_size


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    codes = charset()
    print(f"characters: {len(codes)}")
    css = []
    for w, src in fetch_pretendard().items():
        dst = OUT / f"Pretendard-{w}.woff2"
        size = make(src, dst, codes)
        css.append(f'@font-face {{ font-family: "Pretendard"; src: url("{dst.name}") format("woff2"); font-weight: {w}; font-style: normal; font-display: block; }}')
        print(f"{dst.name}: {size / 1024:.0f} KB")
    for w, src in fetch_serif().items():
        dst = OUT / f"NotoSerifKR-{w}.woff2"
        size = make(src, dst, codes)
        css.append(f'@font-face {{ font-family: "Noto Serif KR"; src: url("{dst.name}") format("woff2"); font-weight: {w}; font-style: normal; font-display: block; }}')
        print(f"{dst.name}: {size / 1024:.0f} KB")
    (OUT / "fonts.css").write_text("/* generated by tools/fonts.py */\n" + "\n".join(css) + "\n", encoding="utf-8")
    print("wrote", OUT / "fonts.css")


if __name__ == "__main__":
    sys.exit(main())
